CREATE TABLE technicians (
  technician_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_code VARCHAR2(30) NOT NULL UNIQUE,
  full_name VARCHAR2(120) NOT NULL,
  email VARCHAR2(180) NOT NULL UNIQUE,
  skill_group VARCHAR2(60) NOT NULL,
  active_flag CHAR(1) DEFAULT 'Y' NOT NULL CHECK (active_flag IN ('Y','N')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE assets (
  asset_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_tag VARCHAR2(40) NOT NULL UNIQUE,
  asset_type VARCHAR2(80) NOT NULL,
  location_name VARCHAR2(120) NOT NULL,
  operational_status VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL
    CHECK (operational_status IN ('ACTIVE','OUT_OF_SERVICE','RETIRED')),
  last_service_date DATE,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE service_requests (
  request_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id NUMBER NOT NULL REFERENCES assets(asset_id),
  requested_by VARCHAR2(120) NOT NULL,
  summary VARCHAR2(240) NOT NULL,
  priority VARCHAR2(20) DEFAULT 'MEDIUM' NOT NULL
    CHECK (priority IN ('LOW','MEDIUM','HIGH','CRITICAL')),
  request_status VARCHAR2(20) DEFAULT 'NEW' NOT NULL
    CHECK (request_status IN ('NEW','APPROVED','REJECTED','CONVERTED')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE work_orders (
  work_order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id NUMBER UNIQUE REFERENCES service_requests(request_id),
  asset_id NUMBER NOT NULL REFERENCES assets(asset_id),
  assigned_technician_id NUMBER REFERENCES technicians(technician_id),
  title VARCHAR2(240) NOT NULL,
  priority VARCHAR2(20) NOT NULL CHECK (priority IN ('LOW','MEDIUM','HIGH','CRITICAL')),
  status VARCHAR2(30) DEFAULT 'OPEN' NOT NULL
    CHECK (status IN ('OPEN','ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED')),
  scheduled_for TIMESTAMP,
  completed_at TIMESTAMP,
  version_no NUMBER DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE work_order_audit (
  audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_order_id NUMBER NOT NULL REFERENCES work_orders(work_order_id),
  old_status VARCHAR2(30),
  new_status VARCHAR2(30) NOT NULL,
  changed_by VARCHAR2(120) NOT NULL,
  changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  notes VARCHAR2(500)
);

CREATE INDEX ix_work_orders_status ON work_orders(status);
CREATE INDEX ix_work_orders_tech ON work_orders(assigned_technician_id);
CREATE INDEX ix_requests_asset ON service_requests(asset_id);
